name: Infracost
on:
  pull_request:
    branches: [ main ]

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  Infracost-Analysis:
    name: Analisar Diferença de Custos
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4

      - name: Setup Infracost
        uses: infracost/actions/setup@v3
        with:
          api_key: ${{ secrets.INFRACOST_API_KEY }}

      # 1. Checkout da branch main para criar a base de comparação
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: main_branch

      # 2. Gera o custo atual da main (Baseline)
      - name: Generate Baseline JSON
        run: |
          infracost breakdown --path main_branch \
                             --format json \
                             --out-file /tmp/infracost-base.json
        env:
          INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}

      # 3. Gera a comparação com as mudanças do seu PR
      - name: Generate Diff JSON
        run: |
          infracost diff --path . \
                         --format json \
                         --compare-to /tmp/infracost-base.json \
                         --out-file /tmp/infracost-diff.json
        env:
          INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}

      # 4. Posta a tabela de custos automática no Pull Request
      - name: Post Infracost comment
        run: |
          infracost comment github --path /tmp/infracost-diff.json \
                                   --repo $GITHUB_REPOSITORY \
                                   --pull-request ${{ github.event.pull_request.number }} \
                                   --github-token ${{ secrets.GITHUB_TOKEN }} \
                                   --behavior update
        env:
          INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}